Update bbr

diff --git a/bbr b/bbr
--- a/bbr
+++ b/bbr
@@ -1,14 +1,9 @@
 #!/usr/bin/env bash
-#
-# Auto install latest kernel for TCP BBR
-#
-# System Required:  CentOS 6+, Debian7+, Ubuntu12+
-#
-# Copyright (C) 2016-2018 Teddysun <i@teddysun.com>
-#
-# URL: https://teddysun.com/489.html
-#
 
+cat /etc/*release | grep DISTRIB_DESCRIPTION | grep "Ubuntu 14.04"; then
+echo "EL SCRIP NO ES COMPATIBLE CON ESTE SISTEMA"
+exit 0
+fi
 red='\033[0;31m'
 green='\033[0;32m'
 yellow='\033[0;33m'
@@ -16,9 +11,9 @@ plain='\033[0m'
 
 cur_dir=$(pwd)
 
-[[ $EUID -ne 0 ]] && echo -e "${red}Error:${plain} This script must be run as root!" && exit 1
+[[ $EUID -ne 0 ]] && echo -e "${red}Error:${plain} LO SENTIMOS ESTE SCRIPT NO ES COMPATIBLE CON TU SERVIDOR!" && exit 1
 
-[[ -d "/proc/vz" ]] && echo -e "${red}Error:${plain} Your VPS is based on OpenVZ, which is not supported." && exit 1
+[[ -d "/proc/vz" ]] && echo -e "${red}Error:${plain} ESTE SCRIPT NO SOPORTA OPENVZ." && exit 1
 
 if [ -f /etc/redhat-release ]; then
     release="centos"
@@ -73,6 +68,8 @@ display_menu(){
     local default=${2}
     eval local arr=(\${${soft}_arr[@]})
     local default_prompt
+    #COMENTAR LO SIGUIENTE ES SOLO PRUEBA
+    default_prompt="(default ${arr[$default-1]})"
     if [[ "$default" != "" ]]; then
         if [[ "$default" == "last" ]]; then
             default=${#arr[@]}
@@ -86,7 +83,7 @@ display_menu(){
 
     while :
     do
-        echo -e "\n------------ ${soft} setting ------------\n"
+        echo -e "\n------------ ${soft} CONFIGURACION ------------\n"
         for ((i=1;i<=${#arr[@]};i++ )); do
             vname="$(get_valid_valname ${arr[$i-1]})"
             hint="$(get_hint $vname)"
@@ -222,7 +219,7 @@ check_kernel_version() {
 install_elrepo() {
 
     if centosversion 5; then
-        echo -e "${red}Error:${plain} not supported CentOS 5."
+        echo -e "${red}Error:${plain} SCRIPT NO SOPORTA CentOS 5."
         exit 1
     fi
 
@@ -272,13 +269,13 @@ reboot_os() {
     echo
     echo -e "${green}Info:${plain} The system needs to reboot."
     #preguna si quiere reiniciar
-    #read -p "Do you want to restart system? [y/n]" is_reboot
-    #if [[ ${is_reboot} == "y" || ${is_reboot} == "Y" ]]; then
+    read -p "Do you want to restart system? [y/n]" is_reboot
+    if [[ ${is_reboot} == "y" || ${is_reboot} == "Y" ]]; then
         reboot
-    #else
-        #echo -e "${green}Info:${plain} Reboot has been canceled..."
+    else
+        echo -e "${green}Info:${plain} Reboot has been canceled..."
         exit 0
-    #fi
+    fi
 }
 
 install_bbr() {
@@ -286,7 +283,7 @@ install_bbr() {
     #checa si se encuenra insalado
     if [ $? -eq 0 ]; then
         echo
-        echo -e "${green}Info:${plain} TCP BBR ya se encuenra instalado..."
+        echo -e "${green}Info:${plain} TCP BBR YA SE ENCUENTRA INSTALADO..."
         exit 0
     fi
     check_kernel_version
@@ -295,7 +292,7 @@ install_bbr() {
         echo
         echo -e "${green}Info:${plain} u kernel version es mayor que 4.9, directly setting TCP BBR..."
         sysctl_config
-        echo -e "${green}Info:${plain} Setting TCP BBR completed..."
+        echo -e "${green}Info:${plain} CONFIGURACION DE TCP BBR COMPLETA..."
         exit 0
     fi
 
@@ -375,17 +372,12 @@ install_bbr() {
 
 
 clear
-#echo "---------- System Information ----------"
-#echo " OS      : $opsy"
-#echo " Arch    : $arch ($lbit Bit)"
-#echo " Kernel  : $kern"
-#echo "----------------------------------------"
-#echo " Auto install latest kernel for TCP BBR"
-#echo
-#echo " URL: https://teddysun.com/489.html"
-#echo "----------------------------------------"
-#echo
-#echo "Press any key to start...or Press Ctrl+C to cancel"
+echo "---------- System Information ----------"
+echo " OS      : $opsy"
+echo " Arch    : $arch ($lbit Bit)"
+echo " Kernel  : $kern"
+echo "----------------------------------------"
+echo " Auto install latest kernel for TCP BBR"
 char=1
 
 install_bbr 2>&1 | tee ${cur_dir}/install_bbr.log
